# Generated by Django 6.0 on 2026-01-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0013_alter_offerimage_where_to_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('blog_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers')),
                ('desc', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
