# Generated by Django 6.0 on 2026-01-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0014_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='carttype',
            field=models.CharField(choices=[('0', 'buy'), ('1', 'rental')], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='rentalprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
