# Generated by Django 6.0 on 2026-01-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0015_cartitem_carttype_product_rentalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availablity',
            field=models.CharField(choices=[('0', 'buy'), ('1', 'rental'), ('2', 'both')], default='0', max_length=10),
        ),
    ]
