# Generated by Django 6.0 on 2026-01-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0016_product_availablity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availablity',
            field=models.CharField(choices=[('0', 'buy'), ('1', 'rental'), ('2', 'both')], default='2', max_length=10),
        ),
    ]
