# Generated by Django 6.0 on 2026-01-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0017_alter_product_availablity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
