# Generated by Django 6.0 on 2026-02-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0019_cartitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='subi', max_length=100),
            preserve_default=False,
        ),
    ]
