# Generated by Django 6.0 on 2026-02-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0020_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/blog'),
        ),
    ]
