# Generated by Django 5.0.6 on 2026-04-18 17:07

import django.db.models.deletion
import ysera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0023_wishlist_wishitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', validators=[ysera.models.validate_image])),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ysera.category'),
        ),
    ]
