# Generated by Django 6.0 on 2026-04-18 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0025_subcategory_typecategory_remove_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ysera.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ysera.typecategory'),
        ),
    ]
