# Generated by Django 6.0 on 2026-05-11 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0026_product_sub_category_product_type_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Typecategory',
            new_name='Collection',
        ),
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Occasion',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type_category',
            new_name='shop_by_collection',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='shop_by_occasion',
        ),
        migrations.AddField(
            model_name='product',
            name='shop_by_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ysera.type'),
        ),
    ]
