# Generated by Django 6.0 on 2026-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0027_type_rename_typecategory_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sizeorcolor',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='varitety',
            field=models.CharField(choices=[('0', 'color'), ('1', 'size')], default='0', max_length=50),
        ),
    ]
