# Generated by Django 6.0 on 2026-05-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0028_product_group_id_product_sizeorcolor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='varitety',
            new_name='variety',
        ),
    ]
