# Generated by Django 6.0 on 2026-05-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0029_rename_varitety_product_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group_id',
            field=models.IntegerField(default=1),
        ),
    ]
