# Generated by Django 5.0.6 on 2026-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysera', '0031_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='save_upto',
            field=models.IntegerField(default=0),
        ),
    ]
